### ISSUE TITLE
Public Elasticsearch+ROR  images 

### ISSUE THREAD

**Issue by sscarduzio** [beshu-tech/ror-sandbox#5]
We should leverage `api.beshu.tech` download APIs to create basic working official ROR images. I.e. with a minimal ACL of a single user. 

Ideally we would extend ES official images, so customers can replace in place that image with ours.

The idea is that a ROR user can either extend our image and copy readonlyrest.yml from their filesystem at build time,  or even more simply, mount the Elasticsearch `conf/` dir, and boot with their own settings entirely.

## Concerns
The amount of images produced must be very high: `supported_es_versions * ror_versions`. 
I believe we can avoid going through older than 8.0.0 ES versions (to begin with). 

## Automation
No automation will be immediately necessary at the moment (only one image will be created 8.0.0 for the latest ROR version) on the first month.

However, this has to become an additional release phase of our CI process in the future.

**Comment by sscarduzio** [comment]
@coutoPL can we close this?

**Comment by coutoPL** [comment]
yes:

https://hub.docker.com/r/beshultd/elasticsearch-readonlyrest
https://hub.docker.com/r/beshultd/kibana-readonlyrest
